// Copyright (c) 2023-2026 ktsu-dev contributors

namespace CodeBlocker.Tests;

using ktsu.CodeBlocker;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Covers the file-level preamble helpers.
/// </summary>
[TestClass]
public sealed class CodeBlockerExtensionsTests
{
	private static CodeBlocker Create() => CodeBlocker.Create(CodeBlocker.DefaultIndentString, NewLines.Lf);

	[TestMethod]
	public void AutoGeneratedHeaderWithoutCopyrightIsJustTheMarker()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker.WriteAutoGeneratedHeader();

		Assert.AreEqual("// <auto-generated />\n\n", codeBlocker.ToString());
	}

	[TestMethod]
	public void AutoGeneratedHeaderPutsTheCopyrightAboveTheMarker()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker.WriteAutoGeneratedHeader("Copyright (c) 2023-2026 ktsu-dev contributors");

		Assert.AreEqual(
			"// Copyright (c) 2023-2026 ktsu-dev contributors\n// <auto-generated />\n\n",
			codeBlocker.ToString());
	}

	[TestMethod]
	public void NullableDirectivesAreWrittenVerbatim()
	{
		using CodeBlocker enable = Create();
		using CodeBlocker disable = Create();

		enable.WriteNullableEnable();
		disable.WriteNullableDisable();

		Assert.AreEqual("#nullable enable\n", enable.ToString());
		Assert.AreEqual("#nullable disable\n", disable.ToString());
	}

	[TestMethod]
	public void FileScopedNamespaceIsFollowedByABlankLine()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker.WriteFileScopedNamespace("Contoso.Widgets");

		Assert.AreEqual("namespace Contoso.Widgets;\n\n", codeBlocker.ToString());
	}

	[TestMethod]
	public void AnEmptyNamespaceWritesNothing()
	{
		using CodeBlocker nullNamespace = Create();
		using CodeBlocker emptyNamespace = Create();

		nullNamespace.WriteFileScopedNamespace(null);
		emptyNamespace.WriteFileScopedNamespace(string.Empty);

		Assert.AreEqual(string.Empty, nullNamespace.ToString());
		Assert.AreEqual(string.Empty, emptyNamespace.ToString());
	}

	[TestMethod]
	public void UsingsAreWrittenOnePerLineAndFollowedByABlankLine()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker.WriteUsings("System", "System.Collections.Generic");

		Assert.AreEqual("using System;\nusing System.Collections.Generic;\n\n", codeBlocker.ToString());
	}

	[TestMethod]
	public void UsingsAreWrittenVerbatimSoAliasesAndStaticImportsWork()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker.WriteUsings("static System.Math", "Text = System.Text");

		Assert.AreEqual("using static System.Math;\nusing Text = System.Text;\n\n", codeBlocker.ToString());
	}

	[TestMethod]
	public void NoUsingsWritesNothingIncludingTheBlankLine()
	{
		// Both overloads, because a generator calls this unconditionally and either spelling has to
		// come out empty rather than leaving a stray blank line at the top of the file.
		using CodeBlocker noArguments = Create();
		using CodeBlocker emptySequence = Create();

		noArguments.WriteUsings();
		emptySequence.WriteUsings(Enumerable.Empty<string>());

		Assert.AreEqual(string.Empty, noArguments.ToString());
		Assert.AreEqual(string.Empty, emptySequence.ToString());
	}

	[TestMethod]
	public void APreambleComposesWithConsistentSpacing()
	{
		using CodeBlocker codeBlocker = Create();

		codeBlocker
			.WriteAutoGeneratedHeader("Copyright (c) 2023-2026 ktsu-dev contributors")
			.WriteNullableEnable()
			.WriteFileScopedNamespace("Contoso.Widgets")
			.WriteUsings("System");

		Assert.AreEqual(
			"""
			// Copyright (c) 2023-2026 ktsu-dev contributors
			// <auto-generated />

			#nullable enable
			namespace Contoso.Widgets;

			using System;


			""".ReplaceLineEndings("\n"),
			codeBlocker.ToString());
	}

	[TestMethod]
	public void NullArgumentsThrow()
	{
		using CodeBlocker codeBlocker = Create();

		Assert.ThrowsExactly<ArgumentNullException>(() => CodeBlockerExtensions.WriteAutoGeneratedHeader(null!));
		Assert.ThrowsExactly<ArgumentNullException>(() => CodeBlockerExtensions.WriteNullableEnable(null!));
		Assert.ThrowsExactly<ArgumentNullException>(() => CodeBlockerExtensions.WriteNullableDisable(null!));
		Assert.ThrowsExactly<ArgumentNullException>(() => CodeBlockerExtensions.WriteFileScopedNamespace(null!, "N"));
		Assert.ThrowsExactly<ArgumentNullException>(() => codeBlocker.WriteUsings((IEnumerable<string>)null!));
	}
}
