// Copyright (c) 2023-2026 ktsu-dev contributors

namespace CodeBlocker.Tests;

using ktsu.CodeBlocker;
using ktsu.CodeBlocker.Templates;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Renders one source file exercising every template kind and pins the result exactly.
/// </summary>
/// <remarks>
/// The expected text below has been compiled as C# — it is valid, and it is what a reviewer would
/// expect a hand-written file to look like. That matters more than any individual assertion here:
/// the model's job is to own the punctuation, spacing and indentation so a generator author does
/// not have to, and a golden file is the only thing that catches a regression in the layout as a
/// whole.
/// </remarks>
[TestClass]
public sealed class TemplateGoldenTests
{
	[TestMethod]
	public void RendersARepresentativeSourceFile()
	{
		SourceFileTemplate file = new()
		{
			FileName = "Widget.g.cs",
			Namespace = "Contoso.Widgets",
			Usings = { "System" },
			Comments = { "// <auto-generated />" },
		};

		ClassTemplate type = new()
		{
			Kind = TypeKind.Class,
			Name = "Widget",
			TypeParameters = { "T" },
			Keywords = { "public", "abstract" },
			BaseClass = "WidgetBase",
			Interfaces = { "IWidget" },
			Constraints = { "where T : struct" },
			Comments = { "/// <summary>A widget.</summary>" },
			Attributes = { "Serializable" },
		};

		type.Members.Add(new FieldTemplate { Type = "int", Name = "count", Keywords = { "private" }, DefaultValue = "0" });
		type.Members.Add(new FieldTemplate { Type = "string", Name = "label", Keywords = { "private" }, DefaultValue = "none", DefaultValueIsQuoted = true });
		type.Members.Add(new PropertyTemplate { Type = "int", Name = "Count", Keywords = { "public" }, Getter = AccessorTemplate.Auto(), Setter = AccessorTemplate.Auto() });
		type.Members.Add(new PropertyTemplate { Type = "int", Name = "Seed", Keywords = { "public" }, Getter = AccessorTemplate.Auto(), Setter = new AccessorTemplate { Modifier = "private" }, DefaultValue = "7" });
		type.Members.Add(new PropertyTemplate { Type = "int", Name = "Doubled", Keywords = { "public" }, ExpressionBodyFactory = cb => cb.Write("count * 2") });
		type.Members.Add(new PropertyTemplate
		{
			Type = "int",
			Name = "Checked",
			Keywords = { "public" },
			Getter = AccessorTemplate.Block(cb =>
			{
				cb.WriteLine("ArgumentOutOfRangeException.ThrowIfNegative(count);");
				cb.WriteLine("return count;");
			}),
		});
		type.Members.Add(new PropertyTemplate { Type = "int", Name = "Abstract", Keywords = { "public", "abstract" }, Getter = AccessorTemplate.Auto() });
		type.Members.Add(new MethodTemplate { Type = "void", Name = "Reset", Keywords = { "public" }, BodyFactory = cb => cb.Write("=> count = 0;") });
		type.Members.Add(new MethodTemplate
		{
			Type = "int",
			Name = "Add",
			Keywords = { "public" },
			Parameters = { new ParameterTemplate { Type = "int", Name = "a" }, new ParameterTemplate { Type = "int", Name = "b", DefaultValue = "1" } },
			BodyFactory = cb =>
			{
				using (new Scope(cb))
				{
					cb.WriteLine("if (a > b)");
					using (new Scope(cb))
					{
						cb.WriteLine("return a;");
					}

					cb.WriteLine("return a + b;");
				}
			},
		});
		type.Members.Add(new MethodTemplate
		{
			Type = "TResult",
			Name = "Map",
			Keywords = { "public" },
			TypeParameters = { "TResult" },
			Parameters = { new ParameterTemplate { Type = "Func<T, TResult>", Name = "selector" } },
			Constraints = { "where TResult : struct" },
			BodyFactory = cb => cb.Write("=> selector(default);"),
		});
		type.Members.Add(new MethodTemplate { Type = "void", Name = "Abstracted", Keywords = { "public", "abstract" }, BodyFactory = null });
		type.Members.Add(new ConstructorTemplate { Name = "Widget", Keywords = { "public" }, Parameters = { new ParameterTemplate { Type = "int", Name = "count" } }, BaseParameters = { "count" } });
		type.Members.Add(new OperatorTemplate
		{
			Type = "Widget<T>",
			Keywords = { "public", "static" },
			Symbol = "+",
			Parameters = { new ParameterTemplate { Type = "Widget<T>", Name = "left" }, new ParameterTemplate { Type = "Widget<T>", Name = "right" } },
			Attributes = { "System.Diagnostics.CodeAnalysis.SuppressMessage(\"Usage\", \"CA2225\")" },
			BodyFactory = cb => cb.Write("=> left;"),
		});
		type.Members.Add(new OperatorTemplate
		{
			Kind = OperatorKind.Implicit,
			Type = "int",
			Keywords = { "public", "static" },
			Parameters = { new ParameterTemplate { Type = "Widget<T>", Name = "widget" } },
			BodyFactory = cb => cb.Write("=> widget.count;"),
		});
		type.NestedClasses.Add(new ClassTemplate { Kind = TypeKind.Enum, Name = "Kind", Keywords = { "private" }, Members = { new EnumMemberTemplate { Name = "Small", DefaultValue = "1" }, new EnumMemberTemplate { Name = "Large" } } });
		type.NestedClasses.Add(new ClassTemplate { Kind = TypeKind.Interface, Name = "IHandle", Keywords = { "private" }, Members = { new MethodTemplate { Type = "void", Name = "Handle" } } });
		type.NestedClasses.Add(new ClassTemplate { Kind = TypeKind.RecordStruct, Name = "Pair", TypeParameters = { "TValue" }, Keywords = { "private", "readonly" }, PositionalParameters = { new ParameterTemplate { Type = "TValue", Name = "First" }, new ParameterTemplate { Type = "TValue", Name = "Second" } } });

		file.Classes.Add(type);

		using CodeBlocker codeBlocker = CodeBlocker.Create(CodeBlocker.DefaultIndentString, NewLines.Lf);
		codeBlocker.AddSourceFile(file);

		// AddSourceFile follows each type with a blank line, so the rendered file ends with one.
		Assert.AreEqual(Expected.ReplaceLineEndings("\n") + "\n\n", codeBlocker.ToString());
	}

	private const string Expected =
		"""
		// <auto-generated />
		namespace Contoso.Widgets;

		using System;

		/// <summary>A widget.</summary>
		[Serializable]
		public abstract class Widget<T> : WidgetBase, IWidget
			where T : struct
		{
			private int count = 0;

			private string label = "none";

			public Widget(int count)
				: base(count) { }

			public int Count { get; set; }

			public int Seed
			{
				get;
				private set;
			} = 7;

			public int Doubled => count * 2;

			public int Checked
			{
				get
				{
					ArgumentOutOfRangeException.ThrowIfNegative(count);
					return count;
				}
			}

			public abstract int Abstract { get; }

			public void Reset() => count = 0;

			public int Add(int a, int b = 1)
			{
				if (a > b)
				{
					return a;
				}
				return a + b;
			}

			public TResult Map<TResult>(Func<T, TResult> selector)
				where TResult : struct => selector(default);

			public abstract void Abstracted();

			[System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2225")]
			public static Widget<T> operator +(Widget<T> left, Widget<T> right) => left;

			public static implicit operator int(Widget<T> widget) => widget.count;

			private enum Kind
			{
				Small = 1,
				Large,
			}

			private interface IHandle
			{
				void Handle();
			}

			private readonly record struct Pair<TValue>(TValue First, TValue Second);
		}
		""";
}
