// Copyright (c) 2023-2026 ktsu-dev contributors

namespace ktsu.CodeBlocker;

/// <summary>
/// Helpers for the file-level shapes that recur in generated C#: the auto-generated preamble, the
/// nullable context, the namespace declaration, and the using directives.
/// </summary>
/// <remarks>
/// Each helper owns the blank line that conventionally follows it, so a preamble assembled from
/// them is spaced consistently no matter which parts a given generator emits.
/// </remarks>
public static class CodeBlockerExtensions
{
	/// <summary>
	/// Writes the preamble that marks a file as generated, followed by a blank line.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <param name="copyright">
	/// An optional copyright line written above the marker, without its <c>//</c> prefix. Pass the
	/// same text the consuming repository's file header template uses.
	/// </param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException"><paramref name="codeBlocker"/> is <see langword="null"/>.</exception>
	public static CodeBlocker WriteAutoGeneratedHeader(this CodeBlocker codeBlocker, string? copyright = null)
	{
		ArgumentNullException.ThrowIfNull(codeBlocker);

		if (!string.IsNullOrEmpty(copyright))
		{
			codeBlocker.WriteLine($"// {copyright}");
		}

		codeBlocker.WriteLine("// <auto-generated />");
		codeBlocker.NewLine();
		return codeBlocker;
	}

	/// <summary>
	/// Writes <c>#nullable enable</c>.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException"><paramref name="codeBlocker"/> is <see langword="null"/>.</exception>
	public static CodeBlocker WriteNullableEnable(this CodeBlocker codeBlocker)
	{
		ArgumentNullException.ThrowIfNull(codeBlocker);

		codeBlocker.WriteLine("#nullable enable");
		return codeBlocker;
	}

	/// <summary>
	/// Writes <c>#nullable disable</c>.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException"><paramref name="codeBlocker"/> is <see langword="null"/>.</exception>
	public static CodeBlocker WriteNullableDisable(this CodeBlocker codeBlocker)
	{
		ArgumentNullException.ThrowIfNull(codeBlocker);

		codeBlocker.WriteLine("#nullable disable");
		return codeBlocker;
	}

	/// <summary>
	/// Writes a file-scoped namespace declaration followed by a blank line, or nothing at all when
	/// no namespace is given.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <param name="namespaceName">The namespace, for example <c>Contoso.Widgets</c>.</param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException"><paramref name="codeBlocker"/> is <see langword="null"/>.</exception>
	public static CodeBlocker WriteFileScopedNamespace(this CodeBlocker codeBlocker, string? namespaceName)
	{
		ArgumentNullException.ThrowIfNull(codeBlocker);

		if (string.IsNullOrEmpty(namespaceName))
		{
			return codeBlocker;
		}

		codeBlocker.WriteLine($"namespace {namespaceName};");
		codeBlocker.NewLine();
		return codeBlocker;
	}

	/// <summary>
	/// Writes one <c>using</c> directive per entry followed by a blank line, or nothing at all when
	/// the sequence is empty.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <param name="usings">
	/// The namespaces to import, without the <c>using</c> keyword or the trailing semicolon. An
	/// entry may carry a modifier or alias — <c>static System.Math</c>, <c>Alias = System.Text</c> —
	/// because it is written verbatim after the keyword.
	/// </param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException">
	/// <paramref name="codeBlocker"/> or <paramref name="usings"/> is <see langword="null"/>.
	/// </exception>
	public static CodeBlocker WriteUsings(this CodeBlocker codeBlocker, IEnumerable<string> usings)
	{
		ArgumentNullException.ThrowIfNull(codeBlocker);
		ArgumentNullException.ThrowIfNull(usings);

		bool wroteAny = false;
		foreach (string usingDirective in usings)
		{
			codeBlocker.WriteLine($"using {usingDirective};");
			wroteAny = true;
		}

		if (wroteAny)
		{
			codeBlocker.NewLine();
		}

		return codeBlocker;
	}

	/// <summary>
	/// Writes one <c>using</c> directive per entry followed by a blank line, or nothing at all when
	/// no namespaces are given.
	/// </summary>
	/// <param name="codeBlocker">The <see cref="CodeBlocker"/> to write to.</param>
	/// <param name="usings">The namespaces to import.</param>
	/// <returns>The same <see cref="CodeBlocker"/>, for chaining.</returns>
	/// <exception cref="ArgumentNullException">
	/// <paramref name="codeBlocker"/> or <paramref name="usings"/> is <see langword="null"/>.
	/// </exception>
	public static CodeBlocker WriteUsings(this CodeBlocker codeBlocker, params string[] usings) =>
		codeBlocker.WriteUsings((IEnumerable<string>)usings);
}
